name: Terraform - Policy Plan and Apply

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: policy-approval
      # aplica só após aprovação

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: tfplan
        run: |
          terraform plan -no-color > tfplan.txt
          cat tfplan.txt

      - name: Comentar Plan no Pull Request
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: tfplan.txt

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.review.state == 'approved')
        run: terraform apply -auto-approve
