name: Terraform Apply Azure Policy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: 'Apply Built-in Azure Policy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        env:
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          tenantId: ${{ secrets.tenantId }}
          subscriptionId: ${{ secrets.subscriptionId }}

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"
        env:
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          tenantId: ${{ secrets.tenantId }}
          subscriptionId: ${{ secrets.subscriptionId }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
        env:
          clientId: ${{ secrets.clientId }}
          clientSecret: ${{ secrets.clientSecret }}
          tenantId: ${{ secrets.tenantId }}
          subscriptionId: ${{ secrets.subscriptionId }}
